version: 1

models:
  gpt-4o:
    providers:
      openai:
        - gpt-4o
      openrouter:
        - openai/gpt-4o
        - openai/gpt-4o-2024-11-20

  claude-3-7-sonnet:
    providers:
      anthropic:
        - claude-3-7-sonnet-20250219
      openrouter:
        - anthropic/claude-3.7-sonnet

  gemini-2.5-flash:
    providers:
      gemini:
        - gemini-2.5-flash
      openrouter:
        - google/gemini-2.5-flash
