"""
@Author: xycdaimi
@Email: xycdaimi@gmail.com
@Date: 2026-05-19
@Description: Gemini Antigravity OAuth 提供商插件
"""
from __future__ import annotations

import asyncio
import random
from datetime import datetime, timedelta, timezone
from typing import Any
from uuid import uuid4

import httpx

from infrastructure.plugins.base import (
    CapacitySignal,
    CredentialPreparationResult,
    EgressMode,
    ProviderPlugin,
)

_TOKEN_ORIGIN = "https://oauth2.googleapis.com"
_TOKEN_URL = f"{_TOKEN_ORIGIN}/token"
_ANTIGRAVITY_BASE_URLS = [
    "https://daily-cloudcode-pa.sandbox.googleapis.com",
    "https://daily-cloudcode-pa.googleapis.com",
    "https://autopush-cloudcode-pa.sandbox.googleapis.com",
]
_ANTIGRAVITY_API_VERSION = "v1internal"
_CLIENT_ID = "1071006060591-tmhssin2h21lcre235vtolojh4g403ep.apps.googleusercontent.com"
_CLIENT_SECRET = "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"
_USER_AGENT = "antigravity/1.104.0 darwin/arm64"


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _generate_project_id() -> str:
    adjectives = ["useful", "bright", "swift", "calm", "bold"]
    nouns = ["fuze", "wave", "spark", "flow", "core"]
    return f"{random.choice(adjectives)}-{random.choice(nouns)}-{uuid4().hex[:5]}"


class AntigravityOauthPlugin(ProviderPlugin):
    PLUGIN_VERSION = "1.0.0"
    PLUGIN_INTERFACE_VERSION = "1.0.0"

    @property
    def name(self) -> str:
        return "antigravity_oauth"

    @property
    def description(self) -> str:
        return (
            "Gemini Antigravity OAuth provider (AIClient2API gemini-antigravity). "
            "Credential is OAuth token JSON generated by Antigravity OAuth."
        )

    @property
    def auth_type(self) -> str:
        return "oauth_json"

    @property
    def credential_hint(self) -> str:
        return (
            '{"access_token":"...",'
            '"refresh_token":"...",'
            '"email":"user@example.com",'
            '"scope":"https://www.googleapis.com/auth/cloud-platform",'
            '"token_type":"Bearer",'
            '"expiry_date":"1776738965000"} '
            "(Gemini Antigravity OAuth credential JSON)"
        )

    @property
    def model_source(self) -> str:
        return "remote"

    @property
    def egress_mode(self) -> EgressMode:
        return "proxy"

    async def verify_upstream_root_reachable(self) -> None:
        await self._ensure_upstream_root_http_reachable(_TOKEN_ORIGIN, httpx.AsyncClient)

    @staticmethod
    def _mask_token(token: str | None) -> str:
        if not token:
            return "missing"
        return token[:8] + "***"

    @staticmethod
    def _expiry_date_ms(credential: dict[str, Any]) -> int | None:
        raw_expiry = credential.get("expiry_date")
        if raw_expiry not in (None, ""):
            try:
                value = int(float(str(raw_expiry)))
            except (TypeError, ValueError):
                return None
            return value if value > 10_000_000_000 else value * 1000

        expired_value = credential.get("expired") or credential.get("expires_at")
        if not expired_value:
            return None
        try:
            parsed = datetime.fromisoformat(str(expired_value).replace("Z", "+00:00"))
        except ValueError:
            return None
        return int(parsed.astimezone(timezone.utc).timestamp() * 1000)

    @classmethod
    def _is_near_expiry(cls, credential: dict[str, Any], near_minutes: int = 20) -> bool:
        expiry_ms = cls._expiry_date_ms(credential)
        if expiry_ms is None:
            return False
        expiry = datetime.fromtimestamp(expiry_ms / 1000, tz=timezone.utc)
        return expiry <= (_utc_now() + timedelta(minutes=near_minutes))

    @staticmethod
    def _drop_none_credential_values(credential: dict[str, Any]) -> dict[str, Any]:
        return {key: value for key, value in credential.items() if value is not None}

    def _normalize_credential(self, credential: dict[str, Any]) -> dict[str, Any]:
        normalized = self._drop_none_credential_values(credential)
        refresh_token = str(normalized.get("refresh_token") or "")
        access_token = str(normalized.get("access_token") or "")
        if not refresh_token and not access_token:
            raise ValueError("credential.refresh_token or credential.access_token is required")
        if refresh_token:
            normalized["refresh_token"] = refresh_token
        if access_token:
            normalized["access_token"] = access_token
        email = str(normalized.get("email") or "").strip()
        if email:
            normalized["email"] = email
        else:
            normalized.pop("email", None)
        normalized["type"] = "gemini_antigravity_oauth"
        if "expiry_date" in normalized:
            expiry_ms = self._expiry_date_ms(normalized)
            if expiry_ms is not None:
                normalized["expiry_date"] = str(expiry_ms)
        return normalized

    @staticmethod
    def _persist_credential(runtime_credential: dict[str, Any]) -> dict[str, Any]:
        return dict(runtime_credential)

    async def _refresh_credential(self, credential: dict[str, Any]) -> dict[str, Any]:
        refresh_token = str(credential.get("refresh_token") or "")
        if not refresh_token:
            raise ValueError("credential.refresh_token is required for token refresh")

        async with self._build_http_client(httpx.AsyncClient) as client:
            response = await client.post(
                _TOKEN_URL,
                data={
                    "client_id": _CLIENT_ID,
                    "client_secret": _CLIENT_SECRET,
                    "refresh_token": refresh_token,
                    "grant_type": "refresh_token",
                },
                headers={
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Accept": "application/json",
                },
            )
            response.raise_for_status()
            payload = response.json()

        access_token = str(payload.get("access_token") or "")
        if not access_token:
            raise ValueError("refresh response missing access_token")
        expires_in = int(payload.get("expires_in") or 3600)
        expiry_date = int((_utc_now() + timedelta(seconds=max(expires_in, 1))).timestamp() * 1000)
        refreshed = {
            **credential,
            "access_token": access_token,
            "refresh_token": str(payload.get("refresh_token") or refresh_token),
            "scope": str(payload.get("scope") or credential.get("scope") or ""),
            "token_type": str(payload.get("token_type") or credential.get("token_type") or "Bearer"),
            "expiry_date": str(expiry_date),
            "last_refresh": _utc_now().isoformat(),
        }
        return self._normalize_credential(refreshed)

    @staticmethod
    def _runtime_headers(runtime_credential: dict[str, Any]) -> dict[str, Any]:
        return {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {runtime_credential['access_token']}",
            "User-Agent": _USER_AGENT,
        }

    async def _antigravity_post(
        self,
        runtime_credential: dict[str, Any],
        method: str,
        body: dict[str, Any],
    ) -> httpx.Response | None:
        last_response: httpx.Response | None = None
        async with self._build_http_client(httpx.AsyncClient) as client:
            for base_url in _ANTIGRAVITY_BASE_URLS:
                try:
                    response = await client.post(
                        f"{base_url}/{_ANTIGRAVITY_API_VERSION}:{method}",
                        headers=self._runtime_headers(runtime_credential),
                        json=body,
                    )
                except Exception:
                    continue
                if response.is_success:
                    return response
                last_response = response
        return last_response

    async def _fetch_available_models(self, runtime_credential: dict[str, Any]) -> httpx.Response | None:
        return await self._antigravity_post(
            runtime_credential,
            "fetchAvailableModels",
            {},
        )

    async def _fetch_models_with_quotas(self, runtime_credential: dict[str, Any]) -> httpx.Response | None:
        return await self._antigravity_post(
            runtime_credential,
            "fetchAvailableModels",
            {"project": runtime_credential["project_id"]},
        )

    @staticmethod
    def _supported_models() -> list[str]:
        return [
            "gemini-3-flash",
            "gemini-3.1-pro-high",
            "gemini-3.1-pro-low",
            "gemini-3.1-flash-image",
            "gemini-3-flash-agent",
            "gemini-2.5-flash",
            "gemini-2.5-flash-lite",
            "gemini-2.5-flash-thinking",
            "gemini-claude-sonnet-4-6",
            "gemini-claude-opus-4-6-thinking",
        ]

    @staticmethod
    def _normalize_model_id(model_id: Any) -> str:
        normalized = str(model_id or "").strip()
        if normalized.startswith("claude-"):
            return f"gemini-{normalized}"
        return normalized

    @classmethod
    def _quota_models_from_payload(cls, payload: dict[str, Any]) -> dict[str, dict[str, Any]] | None:
        raw_models = payload.get("models")
        if not isinstance(raw_models, dict):
            return None

        models: dict[str, dict[str, Any]] = {}
        supported_models = set(cls._supported_models())
        for raw_model_id, model_data in raw_models.items():
            raw_model = str(raw_model_id or "").strip()
            model_id = cls._normalize_model_id(raw_model)
            if not model_id:
                continue
            if model_id not in supported_models and not raw_model.startswith("claude-"):
                continue
            if not isinstance(model_data, dict):
                model_data = {}
            quota_info = model_data.get("quotaInfo")
            quota = quota_info if isinstance(quota_info, dict) else {}
            try:
                remaining = float(
                    quota.get("remainingFraction")
                    if quota.get("remainingFraction") is not None
                    else quota.get("remaining", 0.0)
                )
            except (TypeError, ValueError):
                remaining = 0.0
            models[model_id] = {
                "remaining": max(0.0, min(1.0, remaining)),
                "resetTime": quota.get("resetTime"),
                "resetTimeRaw": quota.get("resetTime"),
            }
        return models

    @classmethod
    def _model_ids_from_payload(cls, payload: dict[str, Any]) -> list[str] | None:
        raw_models = payload.get("models")
        if not isinstance(raw_models, dict):
            return None

        model_ids: list[str] = []
        supported_models = set(cls._supported_models())
        for raw_model_id in raw_models:
            raw_model = str(raw_model_id or "").strip()
            model_id = cls._normalize_model_id(raw_model)
            if model_id and (model_id in supported_models or raw_model.startswith("claude-")):
                model_ids.append(model_id)
        return sorted(dict.fromkeys(model_ids))

    @staticmethod
    def _capacity_signal_from_payload(payload: dict[str, Any]) -> CapacitySignal | None:
        models = AntigravityOauthPlugin._quota_models_from_payload(payload)
        if not models:
            return None
        score = max(float(model_quota.get("remaining") or 0.0) for model_quota in models.values())
        return CapacitySignal(
            has_capacity_signal=True,
            capacity_score=score,
            quota_available=score > 0.0,
            capacity_kind="remaining_ratio",
            reason=f"antigravity_models={len(models)}",
        )

    @staticmethod
    def _extract_project_id(payload: dict[str, Any]) -> str:
        project = payload.get("cloudaicompanionProject")
        if isinstance(project, str):
            return project
        if isinstance(project, dict):
            return str(project.get("id") or project.get("name") or "")
        return ""

    async def _discover_project_id(self, runtime_credential: dict[str, Any]) -> str:
        initial_project_id = ""
        metadata = {
            "ideType": "IDE_UNSPECIFIED",
            "platform": "PLATFORM_UNSPECIFIED",
            "pluginType": "GEMINI",
            "duetProject": initial_project_id,
        }
        try:
            load_response = await self._antigravity_post(
                runtime_credential,
                "loadCodeAssist",
                {
                    "cloudaicompanionProject": initial_project_id,
                    "metadata": metadata,
                },
            )
            if load_response is None:
                return _generate_project_id()
            load_response.raise_for_status()
            load_payload = load_response.json()
            if not isinstance(load_payload, dict):
                return _generate_project_id()

            project_id = self._extract_project_id(load_payload)
            if project_id:
                return project_id

            allowed_tiers = load_payload.get("allowedTiers")
            default_tier = None
            if isinstance(allowed_tiers, list):
                default_tier = next(
                    (tier for tier in allowed_tiers if isinstance(tier, dict) and tier.get("isDefault")),
                    None,
                )
            tier_id = str((default_tier or {}).get("id") or "free-tier")
            onboard_body = {
                "tierId": tier_id,
                "cloudaicompanionProject": initial_project_id,
                "metadata": metadata,
            }

            for _ in range(30):
                onboard_response = await self._antigravity_post(
                    runtime_credential,
                    "onboardUser",
                    onboard_body,
                )
                if onboard_response is None:
                    return _generate_project_id()
                onboard_response.raise_for_status()
                onboard_payload = onboard_response.json()
                if not isinstance(onboard_payload, dict):
                    return _generate_project_id()
                if onboard_payload.get("done"):
                    response_payload = onboard_payload.get("response")
                    if isinstance(response_payload, dict):
                        project = response_payload.get("cloudaicompanionProject")
                        if isinstance(project, dict):
                            project_id = str(project.get("id") or project.get("name") or "")
                        else:
                            project_id = str(project or "")
                    if project_id:
                        return project_id
                await asyncio.sleep(2)
        except Exception:
            return _generate_project_id()

        return _generate_project_id()

    def _normalize_access_credential(self, credential: dict[str, Any]) -> dict[str, Any]:
        normalized = dict(self._normalize_credential(credential))
        if not normalized.get("access_token"):
            raise ValueError("credential.access_token is required")
        return normalized

    def _normalize_project_runtime_credential(self, credential: dict[str, Any]) -> dict[str, Any] | None:
        normalized = self._normalize_access_credential(credential)
        if not str(normalized.get("project_id") or "").strip():
            return None
        return normalized

    def _is_oauth_credential_fresh(self, credential: dict[str, Any]) -> bool:
        normalized = self._normalize_credential(credential)
        if not normalized.get("refresh_token"):
            return bool(normalized.get("access_token"))
        if not normalized.get("access_token"):
            return False
        return not self._is_near_expiry(normalized)

    async def _refresh_oauth_credential(self, credential: dict[str, Any]) -> dict[str, Any] | None:
        try:
            normalized = self._normalize_credential(credential)
            refreshed = await self._refresh_credential(normalized)
        except Exception:
            return None
        return self._persist_credential(refreshed)

    async def _build_runtime_credential(self, credential: dict[str, Any]) -> dict[str, Any]:
        project_id = str(credential.get("project_id") or "").strip()
        normalized = dict(self._normalize_credential(credential))
        runtime_credential = dict(normalized)
        runtime_credential["project_id"] = project_id or await self._discover_project_id(runtime_credential)
        return runtime_credential

    @staticmethod
    def _fallback_models() -> list[str]:
        return AntigravityOauthPlugin._supported_models()

    async def prepare_credential(self, credential: dict[str, Any]) -> CredentialPreparationResult:
        persisted_credential = self._persist_credential(self._normalize_credential(credential))
        return CredentialPreparationResult(
            credential=persisted_credential,
            changed=persisted_credential != credential,
        )

    async def fetch_models(self, credential: dict[str, Any]) -> list[str]:
        try:
            runtime_credential = self._normalize_access_credential(credential)
        except Exception:
            return self._fallback_models()
        response = await self._fetch_available_models(runtime_credential)
        if response is None or not response.is_success:
            return self._fallback_models()

        try:
            payload = response.json()
        except Exception:
            return self._fallback_models()
        if not isinstance(payload, dict):
            return self._fallback_models()

        models = self._model_ids_from_payload(payload)
        if models is None:
            return self._fallback_models()
        return models

    async def is_credential_available(self, credential: dict[str, Any]) -> bool:
        try:
            runtime_credential = self._normalize_access_credential(credential)
        except Exception:
            return False
        response = await self._fetch_available_models(runtime_credential)
        if response is None or not response.is_success:
            return False
        try:
            payload = response.json()
        except Exception:
            return False
        return isinstance(payload, dict) and self._model_ids_from_payload(payload) is not None

    async def get_capacity_signal(self, credential: dict[str, Any]) -> CapacitySignal | None:
        try:
            runtime_credential = self._normalize_project_runtime_credential(credential)
        except Exception:
            return None
        if runtime_credential is None:
            return None
        response = await self._fetch_models_with_quotas(runtime_credential)
        if response is None or not response.is_success:
            return None

        try:
            payload = response.json()
        except Exception:
            return None
        if not isinstance(payload, dict):
            return None
        return self._capacity_signal_from_payload(payload)

    async def explain_credential(self, credential: dict[str, Any]) -> dict:
        try:
            normalized = self._normalize_credential(credential)
            status = "ok"
        except Exception:
            normalized = dict(credential)
            status = "invalid_credential"

        expiry_ms = self._expiry_date_ms(normalized)
        expired = None
        if expiry_ms is not None:
            expired = datetime.fromtimestamp(expiry_ms / 1000, tz=timezone.utc).isoformat()

        return {
            "provider": self.name,
            "status": status,
            "model_source": self.model_source,
            "auth_type": self.auth_type,
            "credential_hint": self._mask_token(normalized.get("access_token")),
            "email": normalized.get("email", ""),
            "type": normalized.get("type", ""),
            "expired": expired,
            "has_refresh_token": bool(normalized.get("refresh_token")),
            "has_project_id": bool(str(normalized.get("project_id") or "").strip()),
        }
