"""
@Author: xycdaimi
@Email: xycdaimi@gmail.com
@Date: 2026-05-12
@Description: Gemini CLI OAuth 提供商插件
"""
from __future__ import annotations

import asyncio
import platform
from datetime import datetime, timedelta, timezone
from typing import Any

import httpx

from infrastructure.plugins.base import (
    CapacitySignal,
    CredentialPreparationResult,
    EgressMode,
    ProviderPlugin,
)

_TOKEN_ORIGIN = "https://oauth2.googleapis.com"
_TOKEN_URL = f"{_TOKEN_ORIGIN}/token"
_CODE_ASSIST_ORIGIN = "https://cloudcode-pa.googleapis.com"
_CODE_ASSIST_BASE_URL = f"{_CODE_ASSIST_ORIGIN}/v1internal"
_CLIENT_ID = "681255809395-oo8ft2oprdrnp9e3aqf6av3hmdib135j.apps.googleusercontent.com"
_CLIENT_SECRET = "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"
_GEMINI_CLI_VERSION = "0.31.0"
_GEMINI_CLI_API_CLIENT = "google-genai-sdk/1.41.0 gl-node/v22.19.0"

def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


class GeminiOauthPlugin(ProviderPlugin):
    PLUGIN_VERSION = "1.0.0"
    PLUGIN_INTERFACE_VERSION = "1.0.0"

    @property
    def name(self) -> str:
        return "gemini_oauth"

    @property
    def description(self) -> str:
        return (
            "Gemini CLI OAuth provider (Google Cloud Code Assist API). "
            "Credential is OAuth token JSON generated by Gemini CLI OAuth."
        )

    @property
    def auth_type(self) -> str:
        return "oauth_json"

    @property
    def credential_hint(self) -> str:
        return (
            '{"access_token":"...",'
            '"refresh_token":"...",'
            '"email":"user@example.com",'
            '"scope":"https://www.googleapis.com/auth/cloud-platform",'
            '"token_type":"Bearer",'
            '"expiry_date":"1776738965000"} '
            "(Gemini CLI OAuth credential JSON)"
        )

    @property
    def model_source(self) -> str:
        return "remote"

    @property
    def egress_mode(self) -> EgressMode:
        return "proxy"

    async def verify_upstream_root_reachable(self) -> None:
        await self._ensure_upstream_root_http_reachable(_TOKEN_ORIGIN, httpx.AsyncClient)

    @staticmethod
    def _mask_token(token: str | None) -> str:
        if not token:
            return "missing"
        return token[:8] + "***"

    @staticmethod
    def _expiry_date_ms(credential: dict[str, Any]) -> int | None:
        raw_expiry = credential.get("expiry_date")
        if raw_expiry not in (None, ""):
            try:
                value = int(float(str(raw_expiry)))
            except (TypeError, ValueError):
                return None
            return value if value > 10_000_000_000 else value * 1000

        expired_value = credential.get("expired") or credential.get("expires_at")
        if not expired_value:
            return None
        try:
            parsed = datetime.fromisoformat(str(expired_value).replace("Z", "+00:00"))
        except ValueError:
            return None
        return int(parsed.astimezone(timezone.utc).timestamp() * 1000)

    @classmethod
    def _is_near_expiry(cls, credential: dict[str, Any], near_minutes: int = 20) -> bool:
        expiry_ms = cls._expiry_date_ms(credential)
        if expiry_ms is None:
            return False
        expiry = datetime.fromtimestamp(expiry_ms / 1000, tz=timezone.utc)
        return expiry <= (_utc_now() + timedelta(minutes=near_minutes))

    @staticmethod
    def _stringify_credential(credential: dict[str, Any]) -> dict[str, str]:
        return {key: str(value) for key, value in credential.items() if value is not None}

    def _normalize_credential(self, credential: dict[str, Any]) -> dict[str, str]:
        normalized = self._stringify_credential(credential)
        if not normalized.get("refresh_token") and not normalized.get("access_token"):
            raise ValueError("credential.refresh_token or credential.access_token is required")
        email = str(normalized.get("email") or "").strip()
        if email:
            normalized["email"] = email
        else:
            normalized.pop("email", None)
        normalized["type"] = "gemini_cli_oauth"
        if "expiry_date" in normalized:
            expiry_ms = self._expiry_date_ms(normalized)
            if expiry_ms is not None:
                normalized["expiry_date"] = str(expiry_ms)
        return normalized

    @staticmethod
    def _persist_credential(runtime_credential: dict[str, str]) -> dict[str, str]:
        return dict(runtime_credential)

    async def _refresh_credential(self, credential: dict[str, Any]) -> dict[str, str]:
        refresh_token = str(credential.get("refresh_token") or "")
        if not refresh_token:
            raise ValueError("credential.refresh_token is required for token refresh")

        async with self._build_http_client(httpx.AsyncClient) as client:
            response = await client.post(
                _TOKEN_URL,
                data={
                    "client_id": _CLIENT_ID,
                    "client_secret": _CLIENT_SECRET,
                    "refresh_token": refresh_token,
                    "grant_type": "refresh_token",
                },
                headers={
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Accept": "application/json",
                },
            )
            response.raise_for_status()
            payload = response.json()

        access_token = str(payload.get("access_token") or "")
        if not access_token:
            raise ValueError("refresh response missing access_token")
        expires_in = int(payload.get("expires_in") or 3600)
        expiry_date = int((_utc_now() + timedelta(seconds=max(expires_in, 1))).timestamp() * 1000)
        refreshed = {
            **credential,
            "access_token": access_token,
            "refresh_token": str(payload.get("refresh_token") or refresh_token),
            "scope": str(payload.get("scope") or credential.get("scope") or ""),
            "token_type": str(payload.get("token_type") or credential.get("token_type") or "Bearer"),
            "expiry_date": str(expiry_date),
            "last_refresh": _utc_now().isoformat(),
        }
        return self._normalize_credential(refreshed)

    @staticmethod
    def _runtime_headers(runtime_credential: dict[str, str], model: str = "unknown") -> dict[str, str]:
        system = platform.system().lower() or "unknown"
        machine = platform.machine().lower() or "unknown"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {runtime_credential['access_token']}",
            "X-Goog-Api-Client": _GEMINI_CLI_API_CLIENT,
        }
        if model not in {"load-code-assist", "onboard-user"}:
            headers["User-Agent"] = f"GeminiCLI/{_GEMINI_CLI_VERSION}/{model} ({system}; {machine})"
        return headers

    @staticmethod
    def _quota_headers(runtime_credential: dict[str, str]) -> dict[str, str]:
        return {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {runtime_credential['access_token']}",
        }

    async def _code_assist_post(
        self,
        runtime_credential: dict[str, str],
        method: str,
        body: dict[str, Any],
        *,
        model: str = "unknown",
    ) -> httpx.Response:
        async with self._build_http_client(httpx.AsyncClient) as client:
            return await client.post(
                f"{_CODE_ASSIST_BASE_URL}:{method}",
                headers=self._runtime_headers(runtime_credential, model),
                json=body,
            )

    async def _retrieve_user_quota(self, runtime_credential: dict[str, str]) -> httpx.Response | None:
        try:
            async with self._build_http_client(httpx.AsyncClient) as client:
                return await client.post(
                    f"{_CODE_ASSIST_BASE_URL}:retrieveUserQuota",
                    headers=self._quota_headers(runtime_credential),
                    json={"project": runtime_credential["project_id"]},
                )
        except Exception:
            return None

    async def _probe_generate_content(
        self,
        runtime_credential: dict[str, str],
        model: str,
    ) -> bool:
        probe_model = str(model or "").strip()
        if not probe_model:
            return False
        try:
            response = await self._code_assist_post(
                runtime_credential,
                "generateContent",
                {
                    "model": probe_model,
                    "project": runtime_credential["project_id"],
                    "request": {
                        "contents": [
                            {
                                "role": "user",
                                "parts": [{"text": "ping"}],
                            }
                        ],
                        "generationConfig": {"maxOutputTokens": 1},
                    },
                },
                model=probe_model,
            )
        except Exception:
            return False
        return response.is_success

    @staticmethod
    def _supported_models() -> list[str]:
        return [
            "gemini-2.5-flash",
            "gemini-2.5-flash-lite",
            "gemini-2.5-pro",
            "gemini-2.5-pro-preview-06-05",
            "gemini-2.5-flash-preview-09-2025",
            "gemini-3-pro-preview",
            "gemini-3-flash-preview",
            "gemini-3.1-pro-preview",
            "gemini-3.1-flash-lite-preview",
        ]

    @classmethod
    def _quota_models_from_payload(cls, payload: dict[str, Any]) -> dict[str, dict[str, Any]] | None:
        buckets = payload.get("buckets")
        if not isinstance(buckets, list):
            return None

        models: dict[str, dict[str, Any]] = {}
        supported_models = set(cls._supported_models())
        for bucket in buckets:
            if not isinstance(bucket, dict):
                continue
            model_id = str(bucket.get("modelId") or "")
            if not model_id or model_id not in supported_models:
                continue
            try:
                remaining = float(bucket.get("remainingFraction") or 0.0)
            except (TypeError, ValueError):
                continue
            models[model_id] = {
                "remaining": max(0.0, min(1.0, remaining)),
                "resetTime": bucket.get("resetTime"),
                "resetTimeRaw": bucket.get("resetTime"),
            }
        return models

    @staticmethod
    def _quota_signal_from_payload(payload: dict[str, Any]) -> CapacitySignal | None:
        models = GeminiOauthPlugin._quota_models_from_payload(payload)
        if models is None:
            return None

        if not models:
            return None

        score = max(float(model_quota.get("remaining") or 0.0) for model_quota in models.values())
        return CapacitySignal(
            has_capacity_signal=True,
            capacity_score=score,
            quota_available=score > 0.0,
            capacity_kind="remaining_ratio",
            reason=f"gemini_models={len(models)}",
        )

    @staticmethod
    def _available_models_from_quota_payload(payload: dict[str, Any]) -> list[str] | None:
        models = GeminiOauthPlugin._quota_models_from_payload(payload)
        if models is None:
            return None
        return sorted(
            model_id
            for model_id, model_quota in models.items()
            if float(model_quota.get("remaining") or 0.0) > 0.0
        )

    @staticmethod
    def _extract_project_id(payload: dict[str, Any]) -> str:
        project = payload.get("cloudaicompanionProject")
        if isinstance(project, str):
            return project
        if isinstance(project, dict):
            return str(project.get("id") or project.get("name") or "")
        return ""

    async def _discover_project_id(self, runtime_credential: dict[str, str]) -> str:
        initial_project_id = ""
        metadata = {
            "ideType": "IDE_UNSPECIFIED",
            "platform": "PLATFORM_UNSPECIFIED",
            "pluginType": "GEMINI",
            "duetProject": initial_project_id,
        }
        load_response = await self._code_assist_post(
            runtime_credential,
            "loadCodeAssist",
            {
                "cloudaicompanionProject": initial_project_id,
                "metadata": metadata,
            },
            model="load-code-assist",
        )
        load_response.raise_for_status()
        load_payload = load_response.json()
        project_id = self._extract_project_id(load_payload)
        if project_id:
            return project_id

        allowed_tiers = load_payload.get("allowedTiers")
        default_tier = None
        if isinstance(allowed_tiers, list):
            default_tier = next(
                (tier for tier in allowed_tiers if isinstance(tier, dict) and tier.get("isDefault")),
                None,
            )
        tier_id = str((default_tier or {}).get("id") or "free-tier")
        onboard_body = {
            "tierId": tier_id,
            "cloudaicompanionProject": initial_project_id,
            "metadata": metadata,
        }

        for _ in range(30):
            onboard_response = await self._code_assist_post(
                runtime_credential,
                "onboardUser",
                onboard_body,
                model="onboard-user",
            )
            onboard_response.raise_for_status()
            onboard_payload = onboard_response.json()
            if onboard_payload.get("done"):
                response_payload = onboard_payload.get("response")
                if isinstance(response_payload, dict):
                    project = response_payload.get("cloudaicompanionProject")
                    if isinstance(project, dict):
                        project_id = str(project.get("id") or project.get("name") or "")
                    else:
                        project_id = str(project or "")
                if project_id:
                    return project_id
            await asyncio.sleep(2)

        raise ValueError("could not discover Gemini project_id")

    def _is_oauth_credential_fresh(self, credential: dict[str, Any]) -> bool:
        normalized = self._normalize_credential(credential)
        if not normalized.get("refresh_token"):
            return bool(normalized.get("access_token"))
        if not normalized.get("access_token"):
            return False
        return not self._is_near_expiry(normalized)

    async def _refresh_oauth_credential(self, credential: dict[str, Any]) -> dict[str, str] | None:
        try:
            normalized = self._normalize_credential(credential)
            refreshed = await self._refresh_credential(normalized)
        except Exception:
            return None
        return self._persist_credential(refreshed)

    async def _build_runtime_credential(self, credential: dict[str, Any]) -> dict[str, str]:
        project_id = str(credential.get("project_id") or "").strip()
        normalized = dict(self._normalize_credential(credential))
        runtime_credential = dict(normalized)
        runtime_credential["project_id"] = project_id or await self._discover_project_id(runtime_credential)
        return runtime_credential

    @staticmethod
    def _fallback_models() -> list[str]:
        return GeminiOauthPlugin._supported_models()

    def _normalize_runtime_credential(self, credential: dict[str, Any]) -> dict[str, str] | None:
        normalized = dict(self._normalize_credential(credential))
        if not str(normalized.get("project_id") or "").strip():
            return None
        return normalized

    async def prepare_credential(self, credential: dict[str, str]) -> CredentialPreparationResult:
        persisted_credential = self._persist_credential(self._normalize_credential(credential))
        return CredentialPreparationResult(
            credential=persisted_credential,
            changed=persisted_credential != credential,
        )

    async def fetch_models(self, credential: dict[str, str]) -> list[str]:
        runtime_credential = self._normalize_runtime_credential(credential)
        if runtime_credential is None:
            return self._fallback_models()
        response = await self._retrieve_user_quota(runtime_credential)
        if response is None or not response.is_success:
            return self._fallback_models()

        try:
            payload = response.json()
        except Exception:
            return self._fallback_models()
        if not isinstance(payload, dict):
            return self._fallback_models()

        models = self._available_models_from_quota_payload(payload)
        if models is None:
            return self._fallback_models()
        return models

    async def is_credential_available(self, credential: dict[str, str]) -> bool:
        try:
            runtime_credential = self._normalize_runtime_credential(credential)
        except Exception:
            return False
        if runtime_credential is None:
            return False
        response = await self._retrieve_user_quota(runtime_credential)
        if response is not None and response.is_success:
            try:
                payload = response.json()
            except Exception:
                payload = None
            if isinstance(payload, dict) and self._quota_models_from_payload(payload) is not None:
                return True
        probe_model = next(iter(self._fallback_models()), "")
        return await self._probe_generate_content(runtime_credential, probe_model)

    async def get_capacity_signal(self, credential: dict[str, str]) -> CapacitySignal | None:
        try:
            runtime_credential = self._normalize_runtime_credential(credential)
        except Exception:
            return None
        if runtime_credential is None:
            return None
        response = await self._retrieve_user_quota(runtime_credential)
        if response is None or not response.is_success:
            return None

        try:
            payload = response.json()
        except Exception:
            return None
        if not isinstance(payload, dict):
            return None
        return self._quota_signal_from_payload(payload)

    async def explain_credential(self, credential: dict[str, str]) -> dict:
        try:
            normalized = self._normalize_credential(credential)
            status = "ok"
        except Exception:
            normalized = dict(credential)
            status = "invalid_credential"

        expiry_ms = self._expiry_date_ms(normalized)
        expired = None
        if expiry_ms is not None:
            expired = datetime.fromtimestamp(expiry_ms / 1000, tz=timezone.utc).isoformat()

        return {
            "provider": self.name,
            "status": status,
            "model_source": self.model_source,
            "auth_type": self.auth_type,
            "credential_hint": self._mask_token(normalized.get("access_token")),
            "email": normalized.get("email", ""),
            "type": normalized.get("type", ""),
            "expired": expired,
            "has_refresh_token": bool(normalized.get("refresh_token")),
        }
